[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
actix-cors = "0.6.1"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.8"
serde_json = "1.0.59"
serde = { version = "1.0.136", features = ["derive"] }